[package]
name = "physp"
version = "0.1.0"
edition = "2021"

[dependencies]
chaos-framework = "0.1.2"
glfw = "0.57.0"
rapier3d = { version = "0.22.0", features = ["parallel", "simd-stable"] }
tokio = { version = "1.40.0", features = ["full"] }
